version: '3.9'

services:
  dabsoft_app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: dabsoft
    container_name: dabsoft_app
    volumes:
      - ./:/app
    restart: always
    ports:
      - "8030:80"
    depends_on:
      - dabsoft_db
      - dabsoft_phpmyadmin
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=dabsoft_db
      - DB_PORT=3306
      - DB_DATABASE=dabsoft
      - MYSQL_USER=local_dev
      - MYSQL_PASSWORD=password
    networks:
      - backend

  composer_dabsoft:
    image: composer:latest
    container_name: composer_dabsoft
    volumes:
      - ./:/app/
    working_dir: /app/
    entrypoint: [ 'composer' ]

  npm_dabsoft:
    image: node:current-alpine
    container_name: npm_dabsoft
    volumes:
      - ./:/app/
    ports:
      - "3010:3010"
    working_dir: /app/
    entrypoint: [ 'npm' ]

  dabsoft_db:
    image: mysql:8.0
    container_name: dabsoft_db
    volumes:
      - dabsoft_data:/var/lib/mysql
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=password_root
      - MYSQL_DATABASE=dabsoft
      - MYSQL_USER=local_dev
      - MYSQL_PASSWORD=password
    networks:
      - backend

  dabsoft_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dabsoft_phpmyadmin
    restart: always
    ports:
      - "8031:80"
    depends_on:
      - dabsoft_db
    environment:
      - PMA_HOST=dabsoft_db
      - MYSQL_ROOT_PASSWORD=password_root
    networks:
      - backend


volumes:
  dabsoft_data:


networks:
  backend:
    driver: bridge